### ISSUE TITLE
Wallbox pulsar without plus

### ISSUE THREAD

**Issue by amgstone** [syssi/esphome-config-examples#7]
I bought myself a Wallbox pulsar, it has bluetooth on board, but no wi-fi and I can't integrate it into HA. It has rs485 on board, maybe it is possible to integrate it into HA via rs485 and esp32?
![Pulsar-EVC-Black-1](https://github.com/syssi/esphome-smg-ii/assets/63303107/da4a58b5-d456-477e-8405-3458b4e3a37d)

**Comment by syssi** [comment]
Do you ask the manufacturer about the Modbus registers or RS485 protocol details?

**Comment by amgstone** [comment]
there is no such information on the Internet

**Comment by syssi** [comment]
It looks like the wallbox cannot be controlled using RS485. The RS485 port is used to talk to a power meter to reduce the power consumption if not enough power is available. The wallbox is the Modbus Master in this scenario and the power meter the slave. If you attach a ESP + RS485 converter to the wallbox you should see some periodic requests.

This project did a traffic capture already: https://github.com/relyd/modbussniffer
