### ISSUE TITLE
Support for Cosuper SPE5000?

### ISSUE THREAD

**Issue by bartixmayo** [syssi/esphome-config-examples#8]
Great job! I wonder if this configuration would work with Cosuper SPE5000-PR248L inverter with the Modbus protocol mentioned below.
[Cosuper Modbus protocol.pdf](https://github.com/syssi/esphome-smg-ii/files/12117739/Cosuper.Modbus.protocol.pdf)
![Cosuper SPE5000-PR248L](https://github.com/syssi/esphome-smg-ii/assets/121507161/b0e29294-b9e7-49bd-8bf9-a2c34b8a78fb)

**Comment by syssi** [comment]
I've moved this issue to another project: https://github.com/syssi/esphome-config-examples/issues/8

Please ping me if you own the device and it's up and running. I will provide some support to talk to the device.
